"""Update Diary model

Revision ID: 06c84e43f468
Revises: 0675cb29abce
Create Date: 2025-09-30 12:51:35.197889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '06c84e43f468'
down_revision: Union[str, Sequence[str], None] = '0675cb29abce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_title'), table_name='notes')
    op.drop_table('notes')
    op.add_column('diaries', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('diaries', sa.Column('preview', sa.String(length=1024), nullable=True))
    op.add_column('diaries', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('diaries', sa.Column('category', sa.Enum('diary', 'checklist', 'idea', 'journal', 'reminder', name='diarycategory'), nullable=True))
    op.add_column('diaries', sa.Column('has_attachment', sa.Boolean(), nullable=True))
    op.add_column('diaries', sa.Column('progress_percent', sa.Float(), nullable=True))
    op.create_index(op.f('ix_diaries_title'), 'diaries', ['title'], unique=False)
    op.drop_column('diaries', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diaries', sa.Column('content', mysql.VARCHAR(collation='utf8mb4_bin', length=4096), nullable=True))
    op.drop_index(op.f('ix_diaries_title'), table_name='diaries')
    op.drop_column('diaries', 'progress_percent')
    op.drop_column('diaries', 'has_attachment')
    op.drop_column('diaries', 'category')
    op.drop_column('diaries', 'date')
    op.drop_column('diaries', 'preview')
    op.drop_column('diaries', 'title')
    op.create_table('notes',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=True),
    sa.Column('preview', mysql.VARCHAR(collation='utf8mb4_bin', length=1024), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('category', mysql.ENUM('diary', 'checklist', 'idea', 'journal', 'reminder'), nullable=True),
    sa.Column('has_attachment', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('progress_percent', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_notes_title'), 'notes', ['title'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    # ### end Alembic commands ###
